sonar.projectKey=migerusecurity07
sonar.working.directory=C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\source\\repos\\cutLab\\PassValidator
sonar.pullrequest.cache.basepath=C:\\source\\repos\\cutLab\\PassValidator
sonar.sources=\
"C:\\source\\repos\\cutLab\\PassValidator\\.github\\workflows\\sonar.yml"

CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.projectKey=migerusecurity07:CAC7B199-A534-3F49-4AEF-C91461A08DBF
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.projectName=PassValidator.Core
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.projectBaseDir=C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.sourceEncoding=utf-8
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.tests=
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.sources=\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core\\PassValidatorService.cs",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core\\obj\\PassValidator.Core.csproj.nuget.dgspec.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core\\obj\\project.assets.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core\\bin\\Debug\\net10.0\\PassValidator.Core.deps.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core\\obj\\Debug\\net10.0\\PassValidator.Core.sourcelink.json"

CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.cs.analyzer.projectOutPaths=\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\0",\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\2"
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.cs.roslyn.reportFilePaths=\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\0\\Issues.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\2\\Issues.json"
CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.cs.scanner.telemetry=\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\0\\Telemetry.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\2\\Telemetry.json"

CAC7B199-A534-3F49-4AEF-C91461A08DBF.sonar.working.directory=C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\.sonar\\mod0
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.projectKey=migerusecurity07:D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.projectName=PassValidator.Core.Tests
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.projectBaseDir=C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.sourceEncoding=utf-8
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.sources=
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.tests=\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests\\obj\\PassValidator.Core.Tests.csproj.nuget.dgspec.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests\\obj\\project.assets.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests\\bin\\Debug\\net10.0\\PassValidator.Core.Tests.deps.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests\\bin\\Debug\\net10.0\\PassValidator.Core.Tests.runtimeconfig.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests\\obj\\Debug\\net10.0\\PassValidator.Core.Tests.sourcelink.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\PassValidator.Core.Tests\\PassValidatorServiceTests.cs"

D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.cs.analyzer.projectOutPaths=\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\1",\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\3"
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.cs.roslyn.reportFilePaths=\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\1\\Issues.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\3\\Issues.json"
D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.cs.scanner.telemetry=\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\1\\Telemetry.json",\
"C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\3\\Telemetry.json"

D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1.sonar.working.directory=C:\\source\\repos\\cutLab\\PassValidator\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=https://sonarcloud.io
sonar.cs.opencover.reportsPaths=**/*.opencover.xml
sonar.organization=migerusecurity07
sonar.exclusions=**/*.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=CAC7B199-A534-3F49-4AEF-C91461A08DBF,D7D3AA18-A69B-0523-5B65-EA9F9FB6DEA1

